samples: "config/samples.tsv"

# Referensi
refs:
  genome: "refs/reference.fasta"
  gff: "refs/reference.gff3"
  protein: "refs/reference_protein.faa"
  cds: "refs/reference_cds.fna" # Optional, hapus jika tidak ada

# Assembly & Polishing
assembly:
  mode: "--nano-hq"
  genome_size: "400m"
medaka:
  model: "r941_min_hac_g507"

# QC
busco:
  lineage: "embryophyta_odb10"

# Repeats
repeats:
  species: "Rice" # Ganti sesuai spesies