samples: "config/samples.tsv"

# Input Reads (Pastikan path ini mengarah ke file yang SUDAH BERSIH)
reads_extension: "fastq.gz" 

# Referensi
refs:
  genome: "refs/reference.fasta"
  gff: "refs/reference.gff3"

# Parameter Assembly (Flye)
assembly:
  mode: "--nano-hq" 
  genome_size: "400m"

# Parameter Polishing (Medaka)
medaka:
  model: "r941_min_hac_g507"

# Parameter Post-Assembly QC (BUSCO)
# Pilih lineage tanaman: viridiplantae_odb10, embryophyta_odb10, atau poales_odb10 (untuk padi/jagung)
busco:
  lineage: "embryophyta_odb10"

# Parameter Repeats
repeats:
  species: "rice"