samples_file: "config/samples.tsv"

# Optimasi: Resource Management
threads:
  assembly: 32
  annotation: 48

# Database Paths (Sesuaikan path ini di server Anda)
databases:
  busco_lineage: "embryophyta_odb10" # atau eudicots_odb10, liliopsida_odb10
  protein_db: "refs/viridiplantae_proteins.fasta" # Untuk BRAKER
  
# Container Paths (Untuk reproducibility)
containers:
  edta: "docker://jianzuoyi/edta:latest"
  braker3: "docker://teambraker/braker3:latest"
  busco: "docker://ezlabgva/busco:v5.4.3_cv1"